### ISSUE TITLE
How to do state preparation

### ISSUE THREAD

**Issue by positr0nium** [rakytap/sequential-quantum-gate-decomposer#97]
In the readme file it says, SQUANDER can do state preparation. When using the search function of the documentation I could however not find any details on how to achieve that. Ideally, I would like to have a function like this

```
def state_preparation_qc(numpy_array):
    # some squander magic
    return qiskit_qc
````

Could you help me in this regard?

**Comment by rakytap** [comment]
I will add an example to the repository on state preparation.

**Comment by positr0nium** [comment]
Appreciate it!

**Comment by rakytap** [comment]
An example is added under examples/state_preparation.

I should mention though, that up to this point we did not perform any exhaustive state preparation experiments. I needed to add some modification to the source code as well, so it would be needed to install sqaunder from GitHub, not from PyPI repository, since it was not updated there yet.

**Comment by positr0nium** [comment]
A fellow Spyder user, I see 😄 Thank you
